Play-travis_to_master
Otus-DevOps-2019-11/AVAstr_infra pull request #1
Opened 2019-12-19 23:21 UTC by AVAstr

HW_ChatOps_for_review

2019-12-20 06:35 UTC, SablinIgor requested changes
Приветствую!

Просьба поправить .travis.yml. После этого заработают тесты и будет видно, что еще нужно поправить test.py.

2019-12-20 06:35 UTC, SablinIgor commented on .travis.yml
> +- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh
Здесь потерялся | bash в конце.
Поэтому тесты фактически не отрабатывали.
Поправьте, и увидите, что 1+1 не равно 1 :)

2019-12-21 22:26 UTC, AVAstr commented on .travis.yml
> +- curl https://raw.githubusercontent.com/express42/otus-homeworks/2019-11/run.sh
@mrgreyves Спасибо, поправил

2019-12-23 06:10 UTC, SablinIgor approved these changes
Приветствую!

Все верно, принимаю ДЗ,

2019-12-23 10:04 UTC, merged